services:
  db:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: yavaarnosi
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  yavaarnosi-api:
    container_name: yavaarnosi-api
    image: yavaar19/yavaarnosi-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped
  yavaarnosi-frontend-react:
    container_name: yavaarnosi-react
    image: yavaar19/yavaarnosi-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - yavaarnosi-api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
